### ISSUE TITLE
Can't fetch yarn packages

### ISSUE THREAD

**Issue by venkatraj** [karanpratapsingh/fullstack-starterkit#13]
When I run `yarn` command, I get this
```
Yarn version: 
  1.22.4

Node version: 
  12.13.1

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/@pm2/js-api/-/js-api-0.6.0.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/home/venkat/.yarn/lib/cli.js:696:66)
      at new ResponseError (/home/venkat/.yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/home/venkat/.yarn/lib/cli.js:67057:16)
      at Request.emit (events.js:210:5)
      at Request.module.exports.Request.onRequestResponse (/home/venkat/.yarn/lib/cli.js:141625:10)
      at ClientRequest.emit (events.js:210:5)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
      at TLSSocket.socketOnData (_http_client.js:456:22)
      at TLSSocket.emit (events.js:210:5)
```

**Comment by venkatraj** [comment]
Never mind. It seems to be an issue with npm servers

**Comment by karanpratapsingh** [comment]
Oh I see, thanks for trying out the project
